FROM gjigsaw/base:20190829-1700
MAINTAINER Python2-Dockerfile@JasonGreen.Name
ENV PYTHON2_IMAGE_BUILT_AFTER 20190829-1700

RUN apt-get install -y \
    python \
    python-dev \
    python-distribute \
    python-pip

RUN pip install \
    ipython
#    pdb
