# Setup docker-compose Aliases
alias dc.build="now docker-compose build"
alias dc.help="now docker-compose help"
alias dc.kill="now docker-compose kill"
alias dc.logs="now docker-compose logs"
alias dc.port="now docker-compose port"
alias dc.ps="now docker-compose ps"
alias dc.pull="now docker-compose pull"
alias dc.rm="now docker-compose rm"
alias dc.run="now docker-compose run"
alias dc.scale="now docker-compose scale"
alias dc.stop="now docker-compose stop"
alias dc.up="now docker-compose up"
alias dc.unuse="docker_compose_unuse"
alias dc.version="docker-compose --version "
