FROM gjigsaw/base:20190829-1700
MAINTAINER audacity-Dockerfile@JasonGreen.Name
ENV AUDACITY_IMAGE_BUILT_AFTER 20190829-1700

RUN apt-get install -y \
   audacity
   
WORKDIR /local

#ENTRYPOINT /usr/local/bin/gource
